name: combiner_ai
description: "Akıllı Kombinler - AI Kombin Uygulaması"
publish_to: 'none' # Bu paketi pub.dev'de yayınlamayı engeller
license: "All Rights Reserved"
version: 0.1.0
homepage: # GitHub repo URL'nizi buraya ekleyebilirsiniz
repository: # GitHub repo URL'nizi buraya ekleyebilirsiniz

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  image: ^4.0.17
  sqflite: ^2.3.0
  path: ^1.8.3
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  http: ^1.1.0
  flutter_image_compress: ^2.1.0
  share_plus: ^11.0.0
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  fluttermoji: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo.png
    - assets/logo (4).png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo (4).png"
  min_sdk_android: 21
  remove_alpha_ios: true
